In [2]:
import ffmpeg
import subprocess

In [7]:
input_file = "./test/frieren_clip1.mp4"
output_file="./test/test_frieren_out.mp4"

#### NOTES

- -b adjusts bitrate, has :v at the end cuz its for video, :a for audio
- -c copies stream, it says "do not re-encode anything, just copy existing streams", so it ignores things like bitrate and anything that encodes. Good for copying exact quality and streams onto new videos

In [ ]:
cmd = [
    "ffmpeg", "-y",
    "-i", input_file,
    "-b:v", "256k",
    "bufsize", "64k", # size of the buffer that smooths spikes, not rly important but cool ig
    output_file
]
print(f"Running:", " ".join(cmd))

subprocess.run(
    cmd,
    stdout = subprocess.PIPE,
    stderr = subprocess.PIPE,
    text=True
)

Running: ffmpeg -y -i ./test/frieren_clip1.mp4 -b:v 256k bufsize 64k ./test/test_frieren_out.mp4


CompletedProcess(args=['ffmpeg', '-y', '-i', './test/frieren_clip1.mp4', '-b:v', '256k', 'bufsize', '64k', './test/test_frieren_out.mp4'], returncode=4294967274, stdout='', stderr="ffmpeg version 8.0-full_build-www.gyan.dev Copyright (c) 2000-2025 the FFmpeg developers\n  built with gcc 15.2.0 (Rev8, Built by MSYS2 project)\n  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-lcms2 --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-libdvdnav --enable-libdvdread --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-liboapv --enable-libqrencode --enable-librav1e --enable-

#### -c:v libx264 breakdown
- -c:v = choose video codec, libx264. It's supported everywhere because it's hardware accelerated universally supported, fast, and many more reasons
- -crf = Constate Rate Factor, name is misleading tho, since it's actually a quality target that controls how aggressively frames are compressed

Why does CRF  require -c:fv? cuz CRF is encoder-specific, it has no idea how to apply it if a codec isn't specified

In [43]:
cmd = [
    "ffmpeg", "-y",
    "-i", input_file,
    "-crf", "30",
    output_file
]

subprocess.run(
    cmd,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

CompletedProcess(args=['ffmpeg', '-y', '-i', './test/frieren_clip1.mp4', '-crf', '30', './test/test_frieren_out.mp4'], returncode=0, stdout=b'', stderr=b"ffmpeg version 8.0-full_build-www.gyan.dev Copyright (c) 2000-2025 the FFmpeg developers\r\n  built with gcc 15.2.0 (Rev8, Built by MSYS2 project)\r\n  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-lcms2 --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-libdvdnav --enable-libdvdread --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-liboapv --enable-libqrencode --enable-librav1e --enable-libsvtav1 --enable-libv

In [11]:
cmd = [
    "ffmpeg", "-y",
    "-i", input_file,
    "-ss", "3",
    "-to", "5",
    output_file
]

subprocess.run(
    cmd,
    stdout = subprocess.PIPE,
    stderr = subprocess.PIPE,
)

CompletedProcess(args=['ffmpeg', '-y', '-i', './test/frieren_clip1.mp4', '-ss', '3', '-to', '5', './test/test_frieren_out.mp4'], returncode=0, stdout=b'', stderr=b"ffmpeg version 8.0-full_build-www.gyan.dev Copyright (c) 2000-2025 the FFmpeg developers\r\n  built with gcc 15.2.0 (Rev8, Built by MSYS2 project)\r\n  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-lcms2 --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-libdvdnav --enable-libdvdread --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-liboapv --enable-libqrencode --enable-librav1e --enable-libsvtav1 --e

#### Learning openCV

In [3]:
import cv2

cap = cv2.VideoCapture("./test/frieren_clip1.mp4")
"""Creates a video capture object:
- OpenCV opens the video file
- Prepares an internal decoder
- Gets ready to read frames sequentially
It basically connects to the video"""


ret, frame = cap.read()
"""1. OpenCV decodes the next frames
   2. Stores the pixel data in frame
   3. Sets ret to: True -> frame read successfully, False otherwise
   FRAME: The frame you're working with"""


if not ret:
    print(f"Failed to read frame")

print(type(frame))
print(frame.shape)
print(frame)

<class 'numpy.ndarray'>
(480, 854, 3)
[[[103  50  30]
  [104  51  31]
  [100  50  29]
  ...
  [173 120  95]
  [172 125  94]
  [169 122  91]]

 [[ 98  45  25]
  [103  50  30]
  [101  51  30]
  ...
  [171 118  93]
  [178 131 100]
  [172 125  94]]

 [[ 88  44  24]
  [ 92  48  28]
  [ 94  50  30]
  ...
  [158 105  80]
  [174 127  96]
  [172 125  94]]

 ...

 [[162 103  47]
  [166 107  51]
  [166 107  51]
  ...
  [176 126  91]
  [179 129  94]
  [177 127  92]]

 [[157  98  42]
  [164 105  49]
  [166 107  51]
  ...
  [179 129  94]
  [182 132  97]
  [178 128  93]]

 [[162 103  47]
  [164 105  49]
  [161 102  46]
  ...
  [179 129  94]
  [180 130  95]
  [177 127  92]]]


In [4]:
"""Calculating mean for scenes and appending to txt"""
import numpy as np
import os
cap = cv2.VideoCapture("./test/frieren_clip1.mp4")
fps = cap.get(cv2.CAP_PROP_FPS)
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
frameNum = 1
sec = 0

out = cv2.VideoWriter(
    "./test/edges.mp4",
    cv2.VideoWriter_fourcc(*"mp4v"),
    fps,
    (width, height),
    isColor=True
)

with open("frame.txt", "w") as f:
    pass
with open("frame.txt", "a") as f:
    while True:
        ret, frame = cap.read()
        if frameNum == 24:
            sec += 1
            frameNum = 0
        if not ret:
            break # if we have no more frames
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) # grayscale data
        edges = cv2.Canny(gray, 50, 100)               # edgedetect data

        edges_bgr = cv2.cvtColor(edges, cv2.COLOR_GRAY2BGR)

        mean_val = edges.mean()
        # print(f"FRAME #{i}: {mean_val}")
        f.write(f"{sec}:{frameNum}: {mean_val}\n")
        
        out.write(edges_bgr)
        frameNum += 1

cap.release()
out.release()

In [ ]:
cmd = [
    "ffmpeg", "-y",
    "-i", input_file,
    "-vf", "drawtext=text='Frame %{means[0]}': x=20:y=20:fontsize=24:fontcolor=white",
    output_file
]

subprocess.run(
    cmd,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

CompletedProcess(args=['ffmpeg', '-y', '-i', './test/frieren_clip1.mp4', '-vf', "drawtext=text='Frame %{means[0]}': x=20:y=20:fontsize=24:fontcolor=white", './test/test_frieren_out.mp4'], returncode=0, stdout=b'', stderr=b"ffmpeg version 8.0-full_build-www.gyan.dev Copyright (c) 2000-2025 the FFmpeg developers\r\n  built with gcc 15.2.0 (Rev8, Built by MSYS2 project)\r\n  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-lcms2 --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-libdvdnav --enable-libdvdread --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-liboapv --

In [13]:
#### Find difference between two scenes

def find_difference(frame1, frame2, threshold):
    difference = abs(frame2 - frame1)
    if difference > threshold:
        return True
    return False

def read_frames(input_file, threshold):
    cap = cv2.VideoCapture(input_file)
    fps = cap.get(cv2.CAP_PROP_FPS)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    with open("frame.txt", "w") as f:
        pass
    
    prev = None
    frameNum = 1
    sec = 0
    with open("frame.txt", "a") as f:
        while True:
            ret, frame = cap.read()
            if frameNum == 24:
                sec += 1
                frameNum = 0
            if not ret:
                break # if we have no more frames
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) # grayscale data (not doing this one rn)
            edges = cv2.Canny(gray, 50, 100)               # edgedetect data

            edges_bgr = cv2.cvtColor(edges, cv2.COLOR_GRAY2BGR)

            mean_val = gray.mean()
            # print(f"FRAME #{i}: {mean_val}")
            f.write(f"{sec}:{frameNum}: {mean_val}")
            
            # Calculate difference between previous frame
            if prev:
                sceneDetected = find_difference(prev, mean_val, threshold) # T/F

                if sceneDetected:
                    f.write(f"  |  DETECTED")

            out.write(edges_bgr)

            f.write("\n")
            frameNum += 1
            prev = mean_val
        

read_frames(input_file=input_file,
            threshold=2.7)